#!/usr/bin/env bash
/usr/bin/env git clone https://github.com/No5stranger/cjp-tmux.git $HOME/.tmux
/usr/bin/env git clone https://github.com/erikw/tmux-powerline.git $HOME/.tmux/tmux-powerline
if [ -f $HOME/.tmux.conf ]
then
    mv $HOME/.tmux.conf $HOME/.tmux.conf.bak
fi
if [ -f $HOME/.tmux-powerlinerc ]
then
    mv $HOME/.tmux-powerlinerc $HOME/.tmux-powerlinerc.bak
fi
cp $HOME/.tmux/cjp.sh $HOME/.tmux/tmux-powerline/themes/cjp.sh
ln -s $HOME/.tmux/tmux.conf $HOME/.tmux.conf
ln -s $HOME/.tmux/tmux-powerlinerc $HOME/.tmux-powerlinerc
